### ISSUE TITLE
messagelist panel alignement fix

### ISSUE THREAD

**Issue by fabiocaccamo** [elky/django-flat-responsive#7]
The green message panel that we see when we save a model is not aligned in responsive mode.

Before:
![schermata 2017-02-07 alle 19 05 34](https://cloud.githubusercontent.com/assets/1035294/22704643/b6ce1554-ed68-11e6-8e07-f1acef2dd29d.png)

Fix:
```css
ul.messagelist li {
    padding-left: 40px;
    background-position-x: 15px;
}
```

After:
![schermata 2017-02-07 alle 19 07 16](https://cloud.githubusercontent.com/assets/1035294/22704658/c253434a-ed68-11e6-87c6-62b9b83ea760.png)
