### ISSUE TITLE
file upload input broken due to input width 100%

### ISSUE THREAD

**Issue by fabiocaccamo** [elky/django-flat-responsive#8]
```css
.aligned .form-row input, 
.aligned .form-row select, 
.aligned .form-row textarea {
    width: 100%;
    margin-right: 0;
    flex: 1 1;
}
```

Fix:
```css
.aligned .form-row .file-upload input {
    width: auto;
}
```
