### ISSUE TITLE
datetime widget broken

### ISSUE THREAD

**Issue by fabiocaccamo** [elky/django-flat-responsive#9]
Before:
![schermata 2017-02-07 alle 19 02 17](https://cloud.githubusercontent.com/assets/1035294/22704450/0d1ca05c-ed68-11e6-860d-1a7c465f7825.png)

Fix:
```css
form .form-row p.datetime {
    ...
    width: 100%;
}
```

After:
![schermata 2017-02-07 alle 19 02 33](https://cloud.githubusercontent.com/assets/1035294/22704477/1f336d0c-ed68-11e6-8ace-159c9b75b92e.png)
